apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
stringData:
  DATABASE_URL: "postgres://platformuser:platformpass123@postgres:5432/platformdb?sslmode=disable"
  POSTGRES_USER: "platformuser"
  POSTGRES_PASSWORD: "platformpass123"
  POSTGRES_DB: "platformdb"
