apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-api-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/duy-tung/platform-engineering.git
    targetRevision: main
    path: deploy/helm/platform-api
    helm:
      valueFiles:
        - values.yaml
        - values-staging.yaml
  destination:
    server: https://136.110.33.133
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
