apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-api-staging
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: app=asia-southeast1-docker.pkg.dev/infra-learning-pdtung1605/platform-images/platform-api
    argocd-image-updater.argoproj.io/app.update-strategy: latest
    argocd-image-updater.argoproj.io/app.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/app.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/write-back-method: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/duy-tung/platform-engineering.git
    targetRevision: main
    path: deploy/helm/platform-api
    helm:
      valueFiles:
        - values.yaml
        - values-staging.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
