apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
- ../../base

# Override image cho staging
images:
- name: platform-api
  newName: asia-southeast1-docker.pkg.dev/infra-learning-pdtung1605/platform-images/platform-api
  newTag: 0e3201c

# Staging-specific patches
patches:
- patch: |
    - op: replace
      path: /spec/replicas
      value: 1
  target:
    kind: Deployment
    name: platform-api
