# Root App for PROD cluster
# kubectl apply -f on prod-cluster to bootstrap all prod workloads
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/duy-tung/platform-engineering.git
    targetRevision: main
    path: deploy/argocd/envs/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
