apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"app":"kiali","app.kubernetes.io/instance":"kiali","app.kubernetes.io/name":"kiali","app.kubernetes.io/part-of":"kiali","app.kubernetes.io/version":"v2.21.0","helm.sh/chart":"kiali-server-2.21.0","version":"v2.21.0"},"name":"kiali","namespace":"istio-system"}}
  creationTimestamp: "2026-02-26T23:50:01Z"
  labels:
    app: kiali
    app.kubernetes.io/instance: kiali
    app.kubernetes.io/name: kiali
    app.kubernetes.io/part-of: kiali
    app.kubernetes.io/version: v2.21.0
    helm.sh/chart: kiali-server-2.21.0
    version: v2.21.0
  name: kiali
  namespace: istio-system
  resourceVersion: "1772149801850671007"
  uid: 75d823b3-034f-4d55-96db-a5152a7e4e8f
