apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: grafana-healthcheck
  namespace: monitoring
spec:
  default:
    config:
      type: HTTP
      httpHealthCheck:
        requestPath: /grafana/api/health
    logConfig:
      enabled: false
  targetRef:
    group: ""
    kind: Service
    name: monitoring-grafana
---
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: argocd-healthcheck
  namespace: argocd
spec:
  default:
    config:
      type: HTTPS
      httpsHealthCheck:
        requestPath: /healthz
    logConfig:
      enabled: false
  targetRef:
    group: ""
    kind: Service
    name: argocd-server
