apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  labels:
    {{- include "platform-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ include "platform-api.databaseUrl" . | quote }}
  POSTGRES_USER: {{ .Values.postgres.credentials.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.credentials.password | quote }}
  POSTGRES_DB: {{ .Values.postgres.credentials.database | quote }}
